#!/bin/sh

test -z $VOICE && VOICE=fred

echo 03 Real criminal shit

say -v victoria "Chapter Three: Real criminal shit."
sleep 3

say -v $VOICE "Before anyone makes any judgement about Julian Assange, he should remind himself once again who (and what) he is who (and what) they are actually dealing with. they are dealing with. Diligent statisticians have calculated that in ten years the small group of activists around WikiLeaks have published TEN MILLION secret documents in ten years. in ten years. More than the entire world press, since the entire world press has even existed. Documents about war crimes, human rights violations, torture, violence, kidnappings, illegal surveillance, espionage, manipulation of opinion and environmental crimes. Relevant publications include diplomatic and military secret papers (of leading belligerent states) as well as documents to make visible the modus operandi of socio-economic organisations and individual actors. organisations and individual actors - (lying) governments, (power-obsessed) party apparatuses, (corrupt) politicians (corrupt) politicians, (unsympathetic) entrepreneurs, (arsehole) corporations and (notorious) egomaniacs, (Swiss) (Swiss) banks, (offshore) fraudsters, (profit-fixated) nature destroyers and finally political (\"Hillary\") and religious (\"Scientology\") sects. WikiLeaks publications were never an end in itself, but a means to achieve a deeply of a profoundly democratic goal, which - borne out of and social ideal2 - is based on the (incontrovertible) conviction that a FREE that a FREE SOCIETY can only be based on FREE INFORMATION. In the WikiLeaks project, the fundamental question of modern democracies is condensed, namely that of the LEGITIMACY of state, intelligence and military information monopolies. WikiLeaks is asking questions that every responsible citizen3 should ask himself and his democratic and his democratic representatives (and uncles): Does a government have the right to (with the aim of retaining power or enriching itself) override the law? Does an intelligence service have the right to violate the privacy rights of citizens? of citizens it has been appointed to protect? Does a military have the right to violate human rights or principles of international law? And, if so, do these organisations also have the right to conceal violations from the public through secrecy? "
sleep 2
say -v $VOICE "Assange, a multi-award-winning journalist and publisher, has been publisher, has been held without legal grounds in the UK’s maximum security Belmarsh prison since April 2019 - along with terrorists and serious criminals, serial killers, sex offenders, Islamists, right-wing extremists, IRA fighters, and Christoph Waltz, who was as Ernst Stavro Blofeld, last used his bionic eye from here to execute the (failed) order to kill James Bond. to kill James Bond. Belmarsh is the British Guantanamo, a strictly geometric breeding facility with clinically white interior cells, a place that has been given the (aptly) nicknamed HELLMARSH. Here sits the WikiLeaks founder has been held in solitary confinement for 30 months despite repeated statements by the United Nations (and others) that he is a victim of arbitrary, illegal detention and psychological torture. There are, must be made clear time and time again that there is NO LEGAL BASIS for the detention of Julian Assange. There is nothing whatsoever against him. Subjective note from Ross Kemp. After watching parts of the documentary \"Welcome to HMP Belmarsh\", for which actor for which actor Ross Kemp (\"EastEnders\") was granted filming and access to the high security prison, we are almost a little relieved that Assange is at least housed in a single room. at least in a single room. And we are appalled, really stunned, that he should be deprived of his of his liberty to force him into a place like this to a place like this without any legal basis. Ross Kemp is a man like like a living room cupboard, and he’s pretty tough. All over the world he has worked among criminal street gangs, in Afghanistan, Papua New Guinea and who knows what else as an embedded journalist without batting an eyelid. When he enters 'The Box', the prison’s high-security unit, and the door closes behind him, he is on the edge of his seat. closes behind him, he is in the most oppressive place in the whole world, he says. whole world, he says. There is no bed, no sink, toilet, no window, no access to water or air. You feel you are completely alone. I don’t think I don’t think I could spend an hour in here without going insane.\"In the first-instance proceedings concerning his extradition District Judge Baraitser had stubbornly refused to allow any of the refused to even take note of any of the obvious facts. of the obvious facts - from the genuinely JOURNALISTIC nature of WikiLeaks’ publications to the recognisably POLITICAL nature of the accusations against its founder, to the obvious (to the blind, really) prospect of an unfair trial in the USA."
sleep 2
say -v $VOICE "Assange would be tried in ALEXANDRIA in the US state of Virginia, where he would have to face a secret trial in a special court with a grand grand jury. In the immediate vicinity of this Washington and Langley, are the Pentagon, the Defense the Pentagon, the Defense Intelligence Agency, the FBI, the CIA, the NSA, and the headquarters of other military, security and intelligence agencies of the United States. The population structure of Alexandria is is about as far from an average urban population as this ridiculous trial is from the rule of from the rule of law. Between 80 and 90 per cent of Alexandria’s residents of legal age, among whom the lay lay judges in the Assange trial would be recruited are representatives of government agencies, intelligence services or the US military, and have a direct, indirect or (at least) economic relationship of dependence on the US government. relationship of dependence on the US government. Grand juries in the relevant judicial district are so reliably one-eyed, one-eared, one-sided, biased and prejudiced that they cannot seriously be expected to render an objective verdict - the burden of loyalty to the government is crushing. In the long the Eastern District Court of Virginia, there has there has never been a single case in which the grand jury has grand jury acquitted a defendant brought by the national security agencies. Truly never. Subjective note from heise.de US legal associations such as the American Association of Jurists (AAJ) and the Center for Constitutional Rights (CCR), together with legal institutions and jurists working internationally, have written a letter to the British Prime Minister. have written a letter to British Prime Minister Boris Johnson and his government to dissuade him from extraditing Julian Assange to the US. Julian Assange from being extradited to the USA. A Such a move would, in their view, be illegal: \"Extradition would be unlawful because the protection of Mr. of Mr Assange’s fundamental due process rights in the is not guaranteed in the USA. Mr Assange will be tried before the notorious 'spy court' of the Eastern District of Virginia (in Alexandria, the author), before which no accused before which no national security defendant has ever succeeded. ever succeeded. Here, he faces a secret trial before a jury selected from a population in which most of the population in which most of the persons eligible for jury eligible for jury selection work for the CIA, NSA, DOD or DOS (The Central Intelligence Agency, The National Security Agency, U.S. Department of Defense, U.S. Department of State) work for or are affiliated with."
sleep 5

say -v Veena "At this stage of the play, we'd like to thank deepl.com (like deep learning dot com) for their free online translation services."

sleep 3
say -v Anna "John Cleese! Bitte nochmals in den Regie-Raum kommen. So geht das mit Ihrer Frau echt nicht! Frechheit! Ich kündige! Was sagen Sie....? Ein Strandhaus? Wo? Moment, wir sind gleich wieder zurück für Sie!"
